from .btc_momentum import BTCMomentumStrategy as BTCMomentumStrategy
from .candle_direction import CandleDirectionStrategy as CandleDirectionStrategy
from .copytrade import CopytradeStrategy as CopytradeStrategy
from .selective_filter import SelectiveFilter as SelectiveFilter
from .streak_reversal import StreakReversalStrategy as StreakReversalStrategy
